package com.alkisstam.sidebar

internal object Prefs {
    const val FILE = "sidebar_prefs"
    const val FAVORITES = "favorites"
    const val SERVICE_ENABLED = "service_enabled"
    const val PILL_HEIGHT = "pill_height"
    const val PILL_WIDTH = "pill_width"
    const val PILL_POSITION = "pill_position"
    const val PILL_SIDE = "pill_side"
    const val PILL_OPACITY = "pill_opacity"
    const val PILL_THEME = "pill_theme"
    const val THEME_CHOICE = "theme_choice"
    const val PANEL_COLOR = "panel_color"
    const val AUTO_HIDE_FULLSCREEN = "auto_hide_fullscreen"
    const val SHOW_LABELS = "show_labels"
    const val VIBRATION = "vibration"
    const val SWIPE_SENSITIVITY = "swipe_sensitivity"
    const val QUICK_CONTROLS_ENABLED = "quick_controls_enabled"
    const val SHOW_TORCH = "show_torch"
    const val SHOW_AUTO_ROTATE = "show_auto_rotate"
    const val SHOW_AUTO_BRIGHTNESS = "show_auto_brightness"
    const val SHOW_RINGER_MODE = "show_ringer_mode"
    const val LAUNCH_TAB = "launch_tab"
    const val SHOW_ALL_APPS = "show_all_apps"
    const val SHOW_EDIT = "show_edit"
    const val GESTURES_ENABLED = "gestures_enabled"
    const val GESTURE_SWIPE_IN = "gesture_swipe_in"
    const val GESTURE_SWIPE_UP = "gesture_swipe_up"
    const val GESTURE_SWIPE_DOWN = "gesture_swipe_down"
    const val GESTURE_DOUBLE_TAP = "gesture_double_tap"
    const val SHOW_BRIGHTNESS_SLIDER = "show_brightness_slider"
    const val SHOW_QUICK_SHARE = "show_quick_share"
    const val SHOW_RECENT_APPS = "show_recent_apps"
    const val SHOW_POWER = "show_power"
    const val SHOW_QR    = "show_qr"
    const val SHOW_DND   = "show_dnd"
}
